name: jake coffman

# Site settings
title: Jake Coffman
header-img: img/home-bg.jpg
email: jake@jakecoffman.com
description: "software development blog"
baseurl: ""
twitter_username: nill
github_username:  jakecoffman

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
