name: jake coffman
url: http://www.jakecoffman.com/
permalink: pretty
relative_permalinks: true

title:               jake coffman
tagline:             'software developer'
description:         'A blog by <a href="https://twitter.com/nill" target="_blank">@nill</a>.'
url:                 http://jakecoffman.com
baseurl:             ''
paginate:            5
paginate_path:       "/blog/_posts/:num"